### PR TITLE
Better problem matching pattern

### LINKED ISSUE #5: problem matcher gets file not found
in `vala-code/package.json` the problemMatcher uses `"fileLocation": "absolute"` which ends up in file not found when clicking on the problem. I think it should be:

```json
"fileLocation": ["relative", "${workspaceRoot}"],
```

### LINKED ISSUE #6: problem matcher doesn't find deprecation warnings
the regexp `^(.*):(\\d+)\\.(\\d+)-(\\d+)\\.(\\d+):\\s+(warning|error):\\s+(.*)$` is doing fine for finding error messages from valac but it doesn't do so well at warnings. I got the the following warning about a deprecation and the format of the line is quite different: `/home/singingbush/gtkproject/src/myapp-gtk.vala:22:2: warning: ‘gtk_color_button_set_rgba’ is deprecated: Use 'gtk_color_chooser_set_rgba' instead`

the following should work in this scenario `^(.*):(\d+):(\d+):\s+(warning):\s+(.*)$`

perhaps instead of just having a $valac problemMatcher there could be $valac-errors and $valac-warnings. That also gives the user more control about what they want to match on: `"problemMatcher": [ "$valac-errors", "$valac-warnings" ]`

### PR DESCRIPTION
**Pull request by dlech**
Also moved pattern to stand-alone "problemPatterns" so that users that want
relative instead of absolute can create their own problemMatcher.

Fixes #5
Fixes #6

### CODE REVIEW

**Comment by dlech** [comment]
This is picking up deprecation warnings for me

Build output of...

```
> Executing task: make -s -C build <

[  6%] Built target doc
[ 37%] Built target conrun
[ 68%] Built target conrun-kill
[ 75%] Generating server/version.c, server/common.c, server/server.c
/home/david/work/ev3dev-dpkg/console-runner/src/server.vala:43.29-43.49: warning: GLib.g_io_error_from_errno has been deprecated since vala-0.16. Use IOError.from_errno
Compilation succeeded - 1 warning(s)
Scanning dependencies of target conrun-server
[ 81%] Building C object src/CMakeFiles/conrun-server.dir/server/version.c.o
[ 87%] Building C object src/CMakeFiles/conrun-server.dir/server/common.c.o
[ 93%] Building C object src/CMakeFiles/conrun-server.dir/server/server.c.o
/home/david/work/ev3dev-dpkg/console-runner/src/server.vala: In function ‘console_runner_server_real_init’:
/home/david/work/ev3dev-dpkg/console-runner/src/server.vala:43:10: error: incompatible types when assigning to type ‘GError * {aka struct _GError *}’ from type ‘GIOErrorEnum {aka enum<anonymous>}’
             var code = (int)g_io_error_from_errno (errno_);
          ^
src/CMakeFiles/conrun-server.dir/build.make:124: recipe for target 'src/CMakeFiles/conrun-server.dir/server/server.c.o' failed
make[2]: *** [src/CMakeFiles/conrun-server.dir/server/server.c.o] Error 1
CMakeFiles/Makefile2:218: recipe for target 'src/CMakeFiles/conrun-server.dir/all' failed
make[1]: *** [src/CMakeFiles/conrun-server.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
The terminal process terminated with exit code: 2

Terminal will be reused by tasks, press any key to close it.
```

results in...

selection_014

**Comment by dlech** [comment]
After this is merged, the wiki should be updated to show the usage:


            "problemMatcher": {
                "fileLocation": "absolute",
                "pattern": "$valac"
            }

**Comment by thiagojedi** [comment]
Thanks for the PR. And sorry for the late response.

After I had a look, I think the problems in #5 can't be fixed with `fileLocation`.

I mean, the problem seem to be that the vala compiler[1] is inconsistent with the paths in the warnings:

```
> Executing task: valac ./src/gtk-hello.vala --pkg=gtk+-3.0 -g <

./src/gtk-hello.vala:1.1-1.8: warning: method `foo' never used
void foo() {
^^^^^^^^
/home/jedi/Projetos/vala-hello-world/src/gtk-hello.vala: In function ‘_vala_main’:
/home/jedi/Projetos/vala-hello-world/src/gtk-hello.vala:29:2: warning: ‘bar’ is deprecated [-Wdeprecated-declarations]
     bar();
  ^
gtk-hello.vala.c:42:6: note: declared here
Compilation succeeded - 1 warning(s)

Terminal will be reused by tasks, press any key to close it.
```

It's nice to have the `fileLocation` option, but I think the default value should be `relative` as it's the default for valac errors:

```
> Executing task: valac ./src/gtk-hello.vala --pkg=gtk+-3.0 -g <

./src/gtk-hello.vala:27.5-27.10: error: syntax error, expected `;'
    window.show_all ();
    ^^^^^^
Compilation failed: 1 error(s), 0 warning(s)
The terminal process terminated with exit code: 1

Terminal will be reused by tasks, press any key to close it.
```

We'll need to document this behavior for users of others toolsets, like the GNU/make you're using.

Is that ok?

-------------------
[1] the compiler version I have is `0.36.5`, avaliable in the elementary OS 0.4.1 Loki

**Comment by dlech** [comment]
> It's nice to have the fileLocation option, but I think the default value should be relative as it's the default for valac errors:

The default is only relative if you supply relative paths to the `valac` command. I send absolute paths to the `valac` command, so I get absolute file names in error messages.

> We'll need to document this behavior for users of others toolsets, like the GNU/make you're using.

Even if you just use `valac` command for full compile, it is still calling gcc internally, which is why you are seeing the inconsistent error messages. The first example you gave is actually a `gcc` error message, not a `valac` error message.

The new regex in this pull request is actually matching both valac and gcc error messages.

---

So, one way of looking at this is to leave "absolute" as the default and encourage people to use absolute paths with `valac` so that they get consistent paths in error messages and have "$valac" in the Vala VS Code extension match both valac and gcc error messages.

The other way to look at is is to only match valac error messages with "$valac" and tell people to also use "$gcc" from the C/C++ VS Code extension to match gcc error messages, in which case a default of "relative" would probably make more sense.

**Comment by dlech** [comment]
ping

**Comment by thiagojedi** [comment]
> So, one way of looking at this is to leave "absolute" as the default and encourage people to use absolute paths with valac so that they get consistent paths in error messages and have "$valac" in the Vala VS Code extension match both valac and gcc error messages.
> 
> The other way to look at is is to only match valac error messages with "$valac" and tell people to also use "$gcc" from the C/C++ VS Code extension to match gcc error messages, in which case a default of "relative" would probably make more sense.

Yes. Consistency is better than to depend on another extension. You got a point.

**Pull request merged**
