### PR TITLE
Add new snippets and update others.

### PR DESCRIPTION
**Pull request by btd1337**
NEW:
- Public Class
- Private Class
- Inheritance Class
- Destructor
- Getter
- Setter
- Getter and Setter
- Printf
- Read Console
- Scan Console

UPDATE:
- GObject Class
- Compact Class
- Main

### CODE REVIEW

**Comment by btd1337** [comment]
Fix: #18

**Comment by thiagojedi** [comment]
Thanks!

**Comment by btd1337** [comment]
@thiagoabreu Could you update the VSCode extension with this change?

**Comment by thiagojedi** [comment]
I'll update it this evening.

**Pull request merged**
